# This file is generated by setup.py. DO NOT EDIT!
from __future__ import absolute_import
from __future__ import division
from __future__ import print_function
from __future__ import unicode_literals
version = '0.9.6'
git_version = '56be2314b36710ac0ce61a68610ab411e80599bd'
