# This file is generated by setup.py. DO NOT EDIT!
from __future__ import absolute_import
from __future__ import division
from __future__ import print_function
from __future__ import unicode_literals
version = '0.9.3'
git_version = 'e6fa00ac2c8f707b476b5c859979ba41ae26b869'
