# This file is generated by setup.py. DO NOT EDIT!
from __future__ import absolute_import
from __future__ import division
from __future__ import print_function
from __future__ import unicode_literals
version = '0.9.5'
git_version = '713360f25da0a989ca26e075a76ccb3b89c925f8'
