name: "ppyolo_onnx"
platform: "onnxruntime_onnx"
max_batch_size : 0
input [
  {
    name: "image"
    data_type: TYPE_FP32
    dims: [-1, 3, 640, 640]
  },
  {
    name: "im_size"
    data_type: TYPE_INT32
    dims: [ -1, 2]
  }
]
output [
  {
    name: "save_infer_model/scale_0.tmp_0"
    data_type: TYPE_FP32
    dims: [6000, 6]
  }
]
