name: Build and Test

on:
  push:
    branches: [ "develop","tese_pir" ]
  pull_request:
    branches: [ "develop","tese_pir" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ '3.8']
        architecture: [ 'x64' ]

    steps:
      # Checkout the latest branch of Paddle2ONNX.
      - name: Checkout Paddle2ONNX
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Build on manylinux2014_x86_64
        uses: docker://paddlepaddle/paddle:paddle2onnx-python3.9-gcc82
        with:
          entrypoint: bash
          args: .github/workflows/scripts/entrypoint.sh ${{ matrix.python-version }} manylinux2014_x86_64

      - name: Setup Python 3.8
        uses: actions/setup-python@v5
        with:
          python-version: '3.8'

      # Install Paddle2ONNX
      - name: Install Paddle2ONNX
        run: |
          python -m pip install dist/*.whl

      # Install Test
      - name: Run Test
        working-directory: ./tests
        run: |
          bash run.sh python
