name: Build and Test

on:
  push:
    branches: [ "develop","tese_pir" ]
  pull_request:
    branches: [ "develop","tese_pir" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ '3.8']
        architecture: [ 'x64' ]

    steps:
      # Checkout the latest branch of Paddle2ONNX.
      - name: Checkout Paddle2ONNX
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Build paddle2onnx and Run tests
        uses: docker://paddlepaddle/paddle:latest-dev-cuda12.3-cudnn9.0-trt8.6-gcc12.2
        with:
          entrypoint: bash
          args: .github/workflows/scripts/entrypoint.sh
