name: Build_Win_amd64

on:
  push:
    branches: [ "release-windows" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: windows-2019
    strategy:
      matrix:
        python-version: [ '3.9' ]
        architecture: [ 'x64' ]

    steps:
    # Step 1: Download and extract protobuf
    - name: Download and extract protobuf
      run: |
        curl -L -o protobuf.zip https://bj.bcebos.com/fastdeploy/third_libs/protobuf-win-x64-3.16.0.zip
        powershell -Command "Expand-Archive -Path protobuf.zip -DestinationPath $PWD/protobuf"

    # Step 2: Set environment variable for Protobuf
    - name: Set Protobuf to PATH
      run: |
        echo "PATH=${{ github.workspace }}/protobuf/bin:$PATH" >> $GITHUB_PATH

    # Step 3: Verify Protobuf installation
    - name: Verify Protobuf installation
      run: |
        $Env:PATH = "${{ github.workspace }}\protobuf\bin;" + $Env:PATH
        echo $Env:PATH
        protoc --version
  
    # Checkout the latest branch of Paddle2ONNX.
    - name: Checkout Paddle2ONNX
      uses: actions/checkout@v4
      with:
        submodules: true

    # Setup Python
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@0b93645e9fea7318ecaed2b359559ac225c90a2b # v5.3.0
      with:
        python-version: ${{ matrix.python-version }}
        architecture: ${{ matrix.architecture }}
    
    # Install Python dependencies
    - name: Install Python dependencies
      run: |
        python -m pip install -q --upgrade pip
        python -m pip install setuptools wheel auditwheel auditwheel-symbols build
    
    - name: Build package
      run: |
        $Env:PATH = "${{ github.workspace }}\protobuf\bin;" + $Env:PATH
        echo $Env:PATH
        dir "${{ github.workspace }}\protobuf\bin"
        protoc --version
        python -m build --wheel
      
